export const contract_address = '0x3fba08a749d5f563c80C8Aa710ca0a6fE06882e1';
export const contract_abi = [
  'constructor(address retiredCarbonCredit_, address roleManager_)',
  'event AuditorAdded(address account, string name, string contact, string location, string website)',
  'event ClaimRequested(uint256 projectId, uint256 co2Reductions, string auditReport, bool verified)',
  'event ProjectAdded(uint256 id, address owner, string name, string location, string description, bool verified, uint256 creditsClaimed)',
  'event ProjectEdited(uint256 id, address owner, string name, string location, string description, bool verified, uint256 creditsClaimed)',
  'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
  'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
  'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
  'function DEFAULT_ADMIN_ROLE() view returns (bytes32) @29000000',
  'function addAuditor(address account_, string name_, string contact_, string location_, string website_) @29000000',
  'function addProject(address account_, string name_, string location_, string description_) @29000000',
  'function auditors(address) view returns (address account, string name, string contact, string location, string website) @29000000',
  'function claims(uint256) view returns (uint256 projectId, uint256 co2Reductions, string auditReport, bool verified) @29000000',
  'function editProject(uint256 id, address account_, string name_, string location_, string description_) @29000000',
  'function getRoleAdmin(bytes32 role) view returns (bytes32) @29000000',
  'function grantRole(bytes32 role, address account) @29000000',
  'function hasRole(bytes32 role, address account) view returns (bool) @29000000',
  'function isRegistered(address account_) view returns (bool result) @29000000',
  'function mint(address account, uint256 id, uint256 amount, bytes data) payable @29000000',
  'function projects(uint256) view returns (uint256 id, address owner, string name, string location, string description, bool verified, uint256 creditsClaimed) @29000000',
  'function renounceRole(bytes32 role, address account) @29000000',
  'function requestCreditsClaim(uint256 projectId_, uint256 co2Reductions_, string auditReport_) @29000000',
  'function retiredCarbonCredit() view returns (address) @29000000',
  'function revokeRole(bytes32 role, address account) @29000000',
  'function roleManager() view returns (address) @29000000',
  'function supportsInterface(bytes4 interfaceId) view returns (bool) @29000000'
]
